name: 'Link Checker: All English'

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout
          repository: Breadcord/Breadcord
      
      - name: debug
        run: tree -d .



